# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 630d8c28671c791f2c80f7522b35ad47243dd5949804c09b86b57b41b990c843321e7b7f99b7b15595e2cd58ea990a5da52cffe25b43b4e1d16eea1cd1f282a5

test:
  secret_key_base: 1bc9d5d7e979c90bf69d4bed9a9fd97fc7bec654c8ab4c65a1fccd011ab02af8a2df1818b867cbcb2c1ef3ea5d7ca5b0b0986da5a6f51c1e1d5ee5a970d00219

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
